config/routes.rb
Rails.application.routes.draw do

  root to: 'frontend#index'

  get "products/:category", to: "frontend#products", as: :category_products
  get "products/multifuncionales/:mark/:stat", to: "frontend#typeprints"
  get "products/multifuncionales/:mark/:stat/:typeprint", to: "frontend#listing_multifunctionals"
  get "supplies/:category", to: "frontend#supplies", as: :category_supplies


  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  resources :admin, only: :index

  scope :admin do
   
  	resources :users do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :marks do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :products do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :budgets do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end
    
  end


  #errors
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all


  #dashboard
  mount KepplerGaDashboard::Engine, :at => '/', as: 'dashboard'

  #message
  mount KepplerContactUs::Engine, :at => '/', as: 'messages'

  #adwords
  mount KepplerAdwords::Engine, :at => '/', as: 'adwords'

  #adword
  #mount KepplerAdwords::Engine, :at => '/', as: 'adwords'

end

app/models/mark.rb
#Generado por keppler
require 'elasticsearch/model'
class Mark < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  has_many :products
  before_save :create_permalink, on: :create
  validates_uniqueness_of :name
  validates_presence_of :name
  
  after_commit on: [:update] do
    puts __elasticsearch__.index_document
  end
  
  def self.searching(query)
    if query
      self.search(self.query query).records.order(id: :desc)
    else
      self.order(id: :desc)
    end
  end

  def self.query(query)
    { query: { multi_match:  { query: query, fields: [:name] , operator: :and }  }, sort: { id: "desc" }, size: self.count }
  end

  #armar indexado de elasticserch
  def as_indexed_json(options={})
    {
      id: self.id.to_s,
      name:  self.name,
      permalink:  self.permalink,
    }.as_json
  end

  private

  def create_permalink
    self.permalink = self.name.downcase.parameterize
  end

end
#Mark.import

app/controllers/marks_controller.rb
#Generado con Keppler.
class MarksController < ApplicationController  
  before_filter :authenticate_user!
  layout 'admin/application'
  load_and_authorize_resource
  before_action :set_mark, only: [:show, :edit, :update, :destroy]

  # GET /marks
  def index
    marks = Mark.searching(@query).all
    @objects, @total = marks.page(@current_page), marks.size
    redirect_to marks_path(page: @current_page.to_i.pred, search: @query) if !@objects.first_page? and @objects.size.zero?
  end

  # GET /marks/1
  def show
  end

  # GET /marks/new
  def new
    @mark = Mark.new
  end

  # GET /marks/1/edit
  def edit
  end

  # POST /marks
  def create
    @mark = Mark.new(mark_params)

    if @mark.save
      redirect_to @mark, notice: 'Mark was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /marks/1
  def update
    if @mark.update(mark_params)
      redirect_to @mark, notice: 'Mark was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /marks/1
  def destroy
    @mark.destroy
    redirect_to marks_url, notice: 'Mark was successfully destroyed.'
  end

  def destroy_multiple
    Mark.destroy redefine_ids(params[:multiple_ids])
    redirect_to marks_path(page: @current_page, search: @query), notice: "Usuarios eliminados satisfactoriamente" 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mark
      @mark = Mark.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def mark_params
      params.require(:mark).permit(:name)
    end
end

app/views/marks/_description.html.haml
.listing-show-header
	%h5
		= material_icon.md_24.bookmark.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.list
		%h5 Módulo de marcas
		%p{align: "justify"} Aquí podra gestionar las marcas de los productos, ofrece opciones para crear, editar, eliminar y visualizar.

app/views/marks/_form.html.haml
.wrapper
	.wrapper-body.container
		.actions
			= link_to marks_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.wrapper-inputs
			.card
				= simple_form_for @mark do |f|
					.row
						= f.input :name, label: "Nombre"

						.form-actions.right
							= f.button :submit, "Guardar", class: "btn"

app/views/marks/_index_show.html.haml
.listing-show-header
	.actions
		- if can? :update, Mark
			= link_to edit_mark_path(@mark), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.bookmark.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	%ul.list
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.id")
			.display-value= @mark.id
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.name")
			.display-value= @mark.name
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.permalink")
			.display-value= @mark.permalink
	

:javascript
	$('.tooltipped').tooltip({delay: 1});

app/views/marks/_listing.html.haml
%tr{ id: "row-#{mark.id}" }
	- if can? :destroy_multiple, Mark
		%td.item-check{style:"width: 10%"}
			= link_to "", mark_path(mark), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{mark.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{mark.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{mark.id}" }

		%td{style:"width: 30%"}
			= link_to "", mark_path(mark, search: @query), remote: true, class: "show-row"
			%span
				= mark.name
								
	%td{style:"width: 5%"}		
		= link_to mark_path(mark), class: "btn-floating waves-effect btn-flat" do
			= material_icon.md_24.more_horiz.css_class("md-dark")

app/views/marks/edit.html.haml
= title "Marcas - editar | #{@mark.id}"
= render 'form'

app/views/marks/index.html.haml
= title("Marcas - Listado")
.listing.col.l9.m12.s12
	- if can? :new, Mark
		= link_to new_mark_path, class: "btn-floating btn-large waves-effect waves-light teal btn-new hide-on-small-only" do
			= material_icon.md_24.add
	= entries(@total, @objects)
	%table.bordered
		%tbody
			- @objects.each do |mark|
				= render 'listing', mark: mark
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							No se han encontrado marks.
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"

- if can? :new, Mark
	= link_to new_mark_path, class: "btn-index-add btn-floating btn-large teal waves-effect waves-light red" do
		= material_icon.md_24.add.css_class("md-light")

app/views/marks/new.html.haml
= title "Marcas - Nuevo"
= render 'form'

app/views/marks/show.html.haml
= title "Marks | #{@mark.id}"
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, Mark
				= link_to mark_path(@mark), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => "Eliminar", method: :delete, data: { confirm: 'Are you sure?' } do
					= material_icon.md_18.delete.css_class("md-dark")	
			- if can? :update, Mark
				= link_to edit_mark_path(@mark), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
					= material_icon.md_18.create.css_class("md-dark")
			= link_to marks_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark") 
		.card			
			%ul.list
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.id")
					.display-value.fs-body-1.tc-black-2= @mark.id.to_s.humanize
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.name")
					.display-value.fs-body-1.tc-black-2= @mark.name.to_s.humanize
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.permalink")
					.display-value.fs-body-1.tc-black-2= @mark.permalink.to_s.humanize

app/views/marks/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@mark.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");