config/routes.rb
Rails.application.routes.draw do

  root to: 'frontend#index'

  get "products/:category", to: "frontend#products", as: :category_products
  get "products/multifuncionales/:mark/:stat", to: "frontend#typeprints"
  get "products/multifuncionales/:mark/:stat/:typeprint", to: "frontend#listing_multifunctionals"
  get "supplies/:category", to: "frontend#supplies", as: :category_supplies


  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  resources :admin, only: :index

  scope :admin do
   
  	resources :users do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :marks do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :products do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :budgets do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end
    
  end


  #errors
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all


  #dashboard
  mount KepplerGaDashboard::Engine, :at => '/', as: 'dashboard'

  #message
  mount KepplerContactUs::Engine, :at => '/', as: 'messages'

  #adwords
  mount KepplerAdwords::Engine, :at => '/', as: 'adwords'

  #adword
  #mount KepplerAdwords::Engine, :at => '/', as: 'adwords'

end

app/models/budget.rb
#Generado por keppler
require 'elasticsearch/model'
class Budget < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  belongs_to :product
  validates_presence_of :email, :name, :city, :phone, :description
  
  after_commit on: [:update] do
    puts __elasticsearch__.index_document
  end
  
  def self.searching(query)
    if query
      self.search(self.query query).records.order(id: :desc)
    else
      self.order(id: :desc)
    end
  end

  def self.query(query)
    { query: { multi_match:  { query: query, fields: [] , operator: :and }  }, sort: { id: "desc" }, size: self.count }
  end

  #armar indexado de elasticserch
  def as_indexed_json(options={})
    {
      id: self.id.to_s,
      email:  self.email.to_s,
      name:  self.name.to_s,
      city:  self.city.to_s,
      phone:  self.phone.to_s,
      origanization:  self.origanization.to_s,
      description:  self.description.to_s,
      product_id:  self.product_id.to_s,
    }.as_json
  end

end
#Budget.import

app/controllers/budgets_controller.rb
#Generado con Keppler.
class BudgetsController < ApplicationController  
  before_filter :authenticate_user!, except: [:create]
  layout 'admin/application'
  load_and_authorize_resource except: [:create]
  before_action :set_budget, only: [:show, :edit, :update, :destroy]

  # GET /budgets
  def index
    budgets = Budget.searching(@query).all
    @objects, @total = budgets.page(@current_page), budgets.size
    redirect_to budgets_path(page: @current_page.to_i.pred, search: @query) if !@objects.first_page? and @objects.size.zero?
  end

  # GET /budgets/1
  def show
  end

  # GET /budgets/new
  def new
    @budget = Budget.new
  end

  # GET /budgets/1/edit
  def edit
  end

  # POST /budgets
  def create
    @budget = Budget.new(budget_params)
    notice = "#{@budget.name}, tu solicitud de cotizacion ha sido enviada correctamente."
    alert = "Por favor, asegurese de ingresar los datos de la cotización de manera correcta."

    if @budget.save
      BudgetMailer.budget_notification(@budget).deliver
      @budget.product ? redirect_to(category_products_path(@budget.product.category.permalink), notice: notice) : redirect_to(root_path, notice: notice)
    else
      
      @budget.product ? redirect_to(category_products_path(@budget.product.category.permalink), alert: alert) : redirect_to(root_path, alert: alert)
    end
  end

  # PATCH/PUT /budgets/1
  def update
    if @budget.update(budget_params)
      redirect_to @budget, notice: 'Budget was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /budgets/1
  def destroy
    @budget.destroy
    redirect_to budgets_url, notice: 'Budget was successfully destroyed.'
  end

  def destroy_multiple
    Budget.destroy redefine_ids(params[:multiple_ids])
    redirect_to budgets_path(page: @current_page, search: @query), notice: "Usuarios eliminados satisfactoriamente" 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_budget
      @budget = Budget.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def budget_params
      params.require(:budget).permit(:email, :name, :city, :phone, :origanization, :description, :product_id)
    end
end

app/views/budgets/_description.html.haml
.listing-show-header
	%h5
		= material_icon.md_24.comment.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.list
		%h5 Descripcion del modulo
		%p{align: "justify"} Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non	proident, sunt in culpa qui officia deserunt mollit anim id est laborum..

app/views/budgets/_form.html.haml
.wrapper
	.wrapper-body.container
		.actions
			= link_to budgets_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.wrapper-inputs
			.card
				= simple_form_for @budget do |f|
					.row
						= f.input :email
						= f.input :name
						= f.input :city
						= f.input :phone
						= f.input :origanization
						= f.input :description, input_html: {class: "materialize-textarea"}
						= f.input :product_id

						.form-actions.right
							= f.button :submit, "Guardar", class: "btn"

app/views/budgets/_index_show.html.haml
.listing-show-header
	.actions
		- if can? :update, Budget
			= link_to edit_budget_path(@budget), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.comment.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	%ul.list
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.id")
			.display-value= @budget.id
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.email")
			.display-value= @budget.email
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.name")
			.display-value= @budget.name
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.city")
			.display-value= @budget.city
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.phone")
			.display-value= @budget.phone
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.origanization")
			.display-value= @budget.origanization
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.description")
			.display-value= @budget.description
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.product_id")
			.display-value= @budget.product ? @budget.product.name : "No ingresado"
	

:javascript
	$(".modal-trigger").leanModal();
	$('.tooltipped').tooltip({delay: 1});

app/views/budgets/_listing.html.haml
%tr{ id: "row-#{budget.id}" }
	- if can? :destroy_multiple, Budget
		%td.item-check{style:"width: 10%"}
			= link_to "", budget_path(budget), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{budget.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{budget.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{budget.id}" }

		%td{style:"width: 30%"}
			= link_to "", budget_path(budget, search: @query), remote: true, class: "show-row"
			%span
				= budget.email
		%td{style:"width: 40%"}
			= link_to "", budget_path(budget, search: @query), remote: true, class: "show-row"
			%span
				= budget.name
		%td{style:"width: 25%"}
			= link_to "", budget_path(budget, search: @query), remote: true, class: "show-row"
			%span
				= budget.phone
								
	%td{style:"width: 5%"}		
		= link_to budget_path(budget), class: "btn-floating waves-effect btn-flat" do
			= material_icon.md_24.more_horiz.css_class("md-dark")

app/views/budgets/edit.html.haml
= title "Budgets - editar | #{@budget.id}"
= render 'form'

app/views/budgets/index.html.haml
= title("Budgets - Listado")
.listing.col.l9.m12.s12
	- if can? :new, model
		= link_to new_budget_path, class: "btn-floating btn-large waves-effect waves-light teal btn-new hide-on-small-only" do
			= material_icon.md_24.add
	= entries(@total, @objects)
	%table.bordered
		%tbody
			- @objects.each do |budget|
				= render 'listing', budget: budget
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							No se han encontrado budgets.
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"

- if can? :new, model
	= link_to new_budget_path, class: "btn-index-add btn-floating btn-large teal waves-effect waves-light red" do
		= material_icon.md_24.add.css_class("md-light")

app/views/budgets/new.html.haml
= title "Budgets - Nuevo"
= render 'form'

app/views/budgets/show.html.haml
= title "Budgets | #{@budget.id}"
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, Budget
				= link_to budget_path(@budget), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => "Eliminar", method: :delete, data: { confirm: 'Are you sure?' } do
					= material_icon.md_18.delete.css_class("md-dark")	
			- if can? :update, Budget
				= link_to edit_budget_path(@budget), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
					= material_icon.md_18.create.css_class("md-dark")
			= link_to budgets_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark") 
		.card			
			%ul.list
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.id")
					.display-value.fs-body-1.tc-black-2= @budget.id
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.email")
					.display-value.fs-body-1.tc-black-2= @budget.email
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.name")
					.display-value.fs-body-1.tc-black-2= @budget.name.humanize
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.city")
					.display-value.fs-body-1.tc-black-2= @budget.city.humanize
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.phone")
					.display-value.fs-body-1.tc-black-2= @budget.phone
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.origanization")
					.display-value.fs-body-1.tc-black-2= @budget.origanization.humanize
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.description")
					.display-value.fs-body-1.tc-black-2= @budget.description.humanize
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.product_id")
					.display-value.fs-body-1.tc-black-2= @budget.product ? @budget.product.name : "No ingresado"

app/views/budgets/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@budget.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");