config/routes.rb
Rails.application.routes.draw do

  root to: 'frontend#index'

  get "products/:category", to: "frontend#products", as: :category_products
  get "products/multifuncionales/:mark/:stat", to: "frontend#typeprints"
  get "products/multifuncionales/:mark/:stat/:typeprint", to: "frontend#listing_multifunctionals"
  get "supplies/:category", to: "frontend#supplies", as: :category_supplies


  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  resources :admin, only: :index

  scope :admin do
   
  	resources :users do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :marks do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :products do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :budgets do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end
    
  end


  #errors
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all


  #dashboard
  mount KepplerGaDashboard::Engine, :at => '/', as: 'dashboard'

  #message
  mount KepplerContactUs::Engine, :at => '/', as: 'messages'

  #adwords
  mount KepplerAdwords::Engine, :at => '/', as: 'adwords'

  #adword
  #mount KepplerAdwords::Engine, :at => '/', as: 'adwords'

end

app/controllers/frontend_controller.rb
class FrontendController < ApplicationController
	layout :resolve_layout
	
  def index
  	@categories = Category.all
    @message = KepplerContactUs::Message.new
    @budget = Budget.new
  end

  # multifunctionals
  def products
  	@category = Category.find_by_permalink(params[:category])
    @message = KepplerContactUs::Message.new
    case @category.permalink
      when "multifuncionales"
        multifuncionales #private method
      when "scanners-profesionales"
        scanners(@category)
      when "plotters"
        plotters(@category)
      when "proyectores"
        proyectores(@category)
    end
  end

  def supplies
    @category = Category.find_by_permalink(params[:category])
    @message = KepplerContactUs::Message.new
    case @category.permalink
      when "suministros"
        suministros(@category) #private method
      when "repuestos"
        repuestos(@category)
      when "toners"
        toners(@category)
      when "otros"
        otros(@category)
    end    
  end

  def typeprints
    @message = KepplerContactUs::Message.new
    @mark = Mark.find_by_permalink(params[:mark])
    @stat = Stat.find_by_permalink(params[:stat])
    @typeprints = Typeprint.first(2)
  end

  def listing_multifunctionals
    @message = KepplerContactUs::Message.new
    @budget = Budget.new
    @mark = Mark.find_by_permalink(params[:mark])
    @stat = Stat.find_by_permalink(params[:stat])
    @typeprint = Typeprint.find_by_permalink(params[:typeprint])
    @products = Product.where(category: 1, mark_id: @mark.id, stat_id: @stat.id, typeprint_id: @typeprint.id).page(params[:page]).per(4)
  end
  # end

  private

  def resolve_layout
    case action_name
	    when "index"
	      "layouts/frontend/application"
	    when "products", "typeprints", "listing_multifunctionals", "supplies"
	      "layouts/frontend/products"
    end
  end

  def multifuncionales
    @marks = Mark.first(2)
    @stats = Stat.first(2)
    @budget = Budget.new
  end

  def scanners(category)
    @products = Product.where(category: category.id).page(params[:page]).per(4)
    @budget = Budget.new
  end

  def plotters(category)
    @products = Product.where(category: category.id).page(params[:page]).per(4)
    @budget = Budget.new
  end

  def proyectores(category)    
    @products = Product.where(category: category.id).page(params[:page]).per(4)
    @budget = Budget.new
  end

  def suministros(category)   
    @products = Product.where(category: category.id).page(params[:page]).per(4)
    @budget = Budget.new  
  end

  def repuestos(category)   
    @products = Product.where(category: category.id).page(params[:page]).per(4)
    @budget = Budget.new  
  end

  def toners(category)   
    @products = Product.where(category: category.id).page(params[:page]).per(4)
    @budget = Budget.new 
  end

  def otros(category) 
    @products = Product.where(category: category.id).page(params[:page]).per(4)
    @budget = Budget.new 
  end

end

app/views/layouts/frontend/_footer.html.haml
%p 
	Todos los derechos reservados 2015. Desarrollado por 
	= link_to "Publinet", "http://publinetecuador.com/", target: "_blank"
	

app/views/layouts/frontend/_google_analytics.html.haml
- if Rails.env.production?
	:javascript
		(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

		ga('create', 'UA-XXXXXXXX-X', 'auto');
		ga('send', 'pageview');

app/views/layouts/frontend/_head.html.haml
%head
	%meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
	%title= content_for?(:title) ? yield(:title) : 'Tecnisupport - Ventas de Copiadoras en Ecuador'
	%meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Venta de copiadoras Ricoh e impresoras empresariales en Quito-Ecuador. Ofrecemos un mejor servicio y pronta respuesta a sus necesidades de Fotocopiado Ricoh.'}"}
	= stylesheet_link_tag 'frontend/application', media: 'all', 'data-turbolinks-track' => true
	%script{src:"https://maps.googleapis.com/maps/api/js?sensor=false"}
	= javascript_include_tag 'frontend/application', 'data-turbolinks-track' => true
	= render 'layouts/frontend/google_analytics'
	= favicon_link_tag "frontend/favicon.png"
	= csrf_meta_tags

app/views/layouts/frontend/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
	- if msg.is_a?(String)
		%div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
			%button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
			%p
				%strong Notificacion:
			= content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/frontend/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top#front-navbar
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = image_tag "frontend/technisupport-navbar.png", class: "brand"
    .collapse.navbar-collapse
      %ul.nav.navbar-nav.top-nav        
        = render 'layouts/frontend/navigation_links'

app/views/layouts/frontend/_navigation_links.html.haml
%li
	= link_to "INICIO", is_index? ? "#home" : root_path, class: "#{'external' unless is_index?}"

%li
	= link_to "EMPRESA", is_index? ? "#about" : root_path(anchor: "about"), class: "#{'external' unless is_index?}"
%li
	= link_to "SOLUCIONES & SERVICIOS", is_index? ? "#services" : root_path(anchor: "services"), class: "#{'external' unless is_index?}"

%li{ class: "#{'current' if products_path?}" }
	= link_to "EQUIPOS", is_index? ? "#products" : root_path(anchor: "products"), class: "#{'external' unless is_index?}"

%li{ class: "#{'current' if supplies_path?}" }
	= link_to "SUMINISTROS & RESPUESTOS", is_index? ? "#supplies" : root_path(anchor: "supplies"), class: "#{'external' unless is_index?} #{'current' if supplies_path?}"
	
%li
	= link_to "CONTACTENOS", "#contact_us"

app/views/layouts/frontend/application.html.haml
!!!
%html
	= render 'layouts/frontend/head' 
	%body
		%header
			= render 'layouts/frontend/navigation'
		%main{:role => "main"}
			= render 'layouts/frontend/messages'
			= yield
		%footer
			= render 'layouts/frontend/footer'

		= render 'keppler_adwords/data'
		- if is_index?
			:javascript
				$( document ).ready(function() {
					setTimeout(function(){
						window.scrollTo(0, $('#'+window.location.hash.substring(1)).offset().top-70)
					}, 1);
				});


			
			

app/views/layouts/frontend/products.html.haml
!!!
%html
	= render 'layouts/frontend/head' 
	%body
		%header
			= render 'layouts/frontend/navigation'
		%main{:role => "main"}
			#products{ style: "margin-top: 70px;"}
				.background
					.container
						.title
							= products_path? ? "EQUIPOS" : "SUMINISTROS & REPUESTOS"
						.subtitle
							-  if products_path?
								Le ofrecemos soluciones tecnológicas concretas para el manejo de sus documentos, que harán que se olvide definitivamente de los costos excesivos.
							- else
								Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
								tempor incididunt ut labore et dolore magna aliqua.
								=action_name
				.container.filters
					= render "layouts/frontend/messages"	
					= yield
				.background#bg-footer
					.container
						.subtitle
							-  if products_path?
								Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
								tempor incididunt ut labore et dolore magna aliqua. Ut enim. Products
							- else
								Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
								tempor incididunt ut labore et dolore magna aliqua. Supplies
				#contact_us
					= render "frontend/landing_partials/contact_us"
		%footer
			= render 'layouts/frontend/footer'