config/routes.rb
Rails.application.routes.draw do

  root to: 'frontend#index'

  get "products/:category", to: "frontend#products", as: :category_products
  get "products/multifuncionales/:mark/:stat", to: "frontend#typeprints"
  get "products/multifuncionales/:mark/:stat/:typeprint", to: "frontend#listing_multifunctionals"
  get "supplies/:category", to: "frontend#supplies", as: :category_supplies


  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  resources :admin, only: :index

  scope :admin do
   
  	resources :users do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :marks do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :products do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :budgets do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end
    
  end


  #errors
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all


  #dashboard
  mount KepplerGaDashboard::Engine, :at => '/', as: 'dashboard'

  #message
  mount KepplerContactUs::Engine, :at => '/', as: 'messages'

  #adwords
  mount KepplerAdwords::Engine, :at => '/', as: 'adwords'

  #adword
  #mount KepplerAdwords::Engine, :at => '/', as: 'adwords'

end

app/models/product.rb
#Generado por keppler
require 'elasticsearch/model'
class Product < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  mount_uploader :image, ImageUploader
  belongs_to :category
  belongs_to :mark
  belongs_to :stat
  belongs_to :typeprint
  has_many :budget
  before_save :create_permalink, on: :create
  validates_uniqueness_of :name
  
  after_commit on: [:update] do
    puts __elasticsearch__.index_document
  end
  
  def self.searching(query)
    if query
      self.search(self.query query).records.order(id: :desc)
    else
      self.order(id: :desc)
    end
  end

  def self.query(query)
    { query: { multi_match:  { query: query, fields: [:id, :name, :price, :category, :mark, :stat, :typeprint] , operator: :and }  }, sort: { id: "desc" }, size: self.count }
  end

  def as_indexed_json(options={})
    {
      id: self.id.to_s,
      name: self.name,
      description: self.description,
      price: self.price.to_s,
      spacification_link: self.spacification_link,
      category: self.category.name,
      mark: self.mark.name,
      stat: self.stat.name,
      typeprint: self.typeprint.name,
    }.as_json
  end


  private

  def create_permalink
    self.permalink = self.name.downcase.parameterize
  end

end
#Product.import

app/controllers/products_controller.rb
#Generado con Keppler.
class ProductsController < ApplicationController  
  before_filter :authenticate_user!
  layout 'admin/application'
  load_and_authorize_resource
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  def index
    products = Product.searching(@query).all
    @objects, @total = products.page(@current_page), products.size
    redirect_to products_path(page: @current_page.to_i.pred, search: @query) if !@objects.first_page? and @objects.size.zero?
  end

  # GET /products/1
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /products/1
  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /products/1
  def destroy
    @product.destroy
    redirect_to products_url, notice: 'Product was successfully destroyed.'
  end

  def destroy_multiple
    Product.destroy redefine_ids(params[:multiple_ids])
    redirect_to products_path(page: @current_page, search: @query), notice: "Usuarios eliminados satisfactoriamente" 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def product_params
      params.require(:product).permit(:image, :name, :description, :attributes_description, :price, :spacification_link, :category_id, :mark_id, :stat_id, :typeprint_id)
    end
end

app/views/products/_description.html.haml
.listing-show-header
	%h5
		= material_icon.md_24.print.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.list
		%h5 Descripcion del modulo
		%p{align: "justify"} Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non	proident, sunt in culpa qui officia deserunt mollit anim id est laborum..

app/views/products/_form.html.haml
.wrapper
	.wrapper-body.container
		.actions
			= link_to products_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.wrapper-inputs
			.card
				= simple_form_for @product do |f|
					.row
						= f.input :image, :as => :file_material, label: false, wrapper_html: { class: "file-field" }
						= f.input :name, label: "Nombre"
						= f.input :price, label: "Precio"
						= f.input :spacification_link, label: "Url de pdf"
						%div
							%label{ style: "position: relative; top: 10px; left: 10px; font-weight: 900; font-size: 1em; color: black;"} Escribir descripción del equipo:
							= f.input :description, :as => :ckeditor, label: false, input_html: { :ckeditor => { :toolbar => 'mini'} }
						%br/
						%label{ style: "position: relative; top: 10px; left: 10px; font-weight: 900; font-size: 1em; color: black;"} Escribir atributos del equipo:
						= f.input :attributes_description, :as => :ckeditor, label: false, input_html: { :ckeditor => { :toolbar => 'mini'} }
						= f.input :category_id, collection: Category.all, label: false, include_blank: "Selecione una categoría", input_html: { class: "browser-default" }
						= f.input :mark_id, collection: Mark.all, label: false, include_blank: "Selecione una marca", input_html: { class: "browser-default" }
						= f.input :stat_id, collection: Stat.all, label: false, include_blank: "Selecione una estado", input_html: { class: "browser-default" }
						= f.input :typeprint_id, collection: Typeprint.all, label: false, include_blank: "Selecione tipo de color", input_html: { class: "browser-default" }

						.form-actions.right
							= f.button :submit, "Guardar", class: "btn"

- if @product.image.file
	:javascript
		$('.file-path').val("#{@product.image.file.filename}")

app/views/products/_index_show.html.haml
.listing-show-header
	.actions
		- if can? :update, Product
			= link_to edit_product_path(@product), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar", 'data-no-turbolink' => true do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.print.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	= image_tag @product.image
	%ul.list
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.id")
			.display-value= @product.id
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.name")
			.display-value= @product.name
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.description")
			.display-value= sanitize(@product.description, tags: []).truncate(300)
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.price")
			.display-value= @product.price
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.spacification_link")
			.display-value= link_to @product.spacification_link, @product.spacification_link, target: "_blank"
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.category_id")
			.display-value= @product.category.name
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.mark_id")
			.display-value= @product.mark.name
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.stat_id")
			.display-value= @product.stat.name
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.typeprint_id")
			.display-value= @product.typeprint.name
	

:javascript
	$(".modal-trigger").leanModal();
	$('.tooltipped').tooltip({delay: 1});

app/views/products/_listing.html.haml
%tr{ id: "row-#{product.id}" }
	- if can? :destroy_multiple, Product
		%td.item-check{style:"width: 10%"}
			= link_to "", product_path(product), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{product.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{product.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{product.id}" }

		%td{style:"width: 40%"}
			= link_to "", product_path(product, search: @query), remote: true, class: "show-row"
			%span
				= product.name
		%td{style:"width: 20%"}
			= link_to "", product_path(product, search: @query), remote: true, class: "show-row"
			%span
				= product.category.name
		%td{style:"width: 20%"}
			= link_to "", product_path(product, search: @query), remote: true, class: "show-row"
			%span
				= product.mark.name
		%td{style:"width: 10%"}
			= link_to "", product_path(product, search: @query), remote: true, class: "show-row"
			%span
				= product.stat.name
		%td{style:"width: 10%"}
			= link_to "", product_path(product, search: @query), remote: true, class: "show-row"
			%span
				= product.typeprint.name
								
	%td{style:"width: 5%"}		
		= link_to product_path(product), class: "btn-floating waves-effect btn-flat" do
			= material_icon.md_24.more_horiz.css_class("md-dark")

app/views/products/edit.html.haml
= title "Productos - editar | #{@product.id}"
= render 'form'

app/views/products/index.html.haml
= title("Porductos - Listado")
.listing.col.l9.m12.s12
	- if can? :new, model
		= link_to new_product_path, class: "btn-floating btn-large waves-effect waves-light teal btn-new hide-on-small-only", 'data-no-turbolink' => true do
			= material_icon.md_24.add
	= entries(@total, @objects)
	%table.bordered
		%tbody
			- @objects.each do |product|
				= render 'listing', product: product
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							No se han encontrado products.
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"

- if can? :new, model
	= link_to new_product_path, class: "btn-index-add btn-floating btn-large teal waves-effect waves-light red" do
		= material_icon.md_24.add.css_class("md-light")

app/views/products/new.html.haml
= title "Productos - Nuevo"
= render 'form'

app/views/products/show.html.haml
= title "Productos | #{@product.id}"
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, Product
				= link_to product_path(@product), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => "Eliminar", method: :delete, data: { confirm: 'Are you sure?' } do
					= material_icon.md_18.delete.css_class("md-dark")	
			- if can? :update, Product
				= link_to edit_product_path(@product), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar", 'data-no-turbolink' => true do
					= material_icon.md_18.create.css_class("md-dark")
			= link_to products_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark") 
		.card
			%center
				= image_tag @product.image	
			%ul.list
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.id")
					.display-value.fs-body-1.tc-black-2= @product.id					
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.name")
					.display-value.fs-body-1.tc-black-2= @product.name.to_s.humanize
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.description")
					.display-value.fs-body-1.tc-black-2= raw @product.description
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.price")
					.display-value.fs-body-1.tc-black-2= @product.price.to_s.humanize
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.spacification_link")
					.display-value.fs-body-1.tc-black-2= link_to @product.spacification_link, @product.spacification_link, target: "_blank"
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.category_id")
					.display-value.fs-body-1.tc-black-2= @product.category.name.humanize
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.mark_id")
					.display-value.fs-body-1.tc-black-2= @product.mark.name.humanize
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.stat_id")
					.display-value.fs-body-1.tc-black-2= @product.stat.name.humanize
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.typeprint_id")
					.display-value.fs-body-1.tc-black-2= @product.typeprint.name.humanize

app/views/products/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@product.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");